Repository lacuna-tech/mds-core, pull requests merged in 2019-10, with the labels that each got.

#21 [mds-compliance] [mds-db] Resolve Geography build errors.
  packages/mds-compliance/api.ts
  packages/mds-db/tests/mds-db.spec.ts
Labels: bug

#23 [mds-compliance] Feature/jane/implement count minimums
  packages/mds-compliance/mds-compliance-engine.ts
  packages/mds-compliance/tests/engine-test.spec.ts
  packages/mds-policy-author/package.json
Labels: size/M

#34 [mds-db] Fix bad Geographies migration script, bump to release/0.0.9
  container-images/env-inject/package.json
  container-images/mds-agency/package.json
  container-images/mds-audit/package.json
  container-images/mds-compliance/package.json
  container-images/mds-daily/package.json
  container-images/mds-metrics-sheet/package.json
  container-images/mds-native/package.json
  container-images/mds-policy-author/package.json
  container-images/mds-policy/package.json
  container-images/mds-provider/package.json
  package.json
  packages/mds-agency/package.json
  packages/mds-api-authorizer/package.json
  packages/mds-api-helpers/package.json
  packages/mds-api-server/package.json
  packages/mds-audit/package.json
  packages/mds-cache/package.json
  packages/mds-compliance/package.json
  packages/mds-daily/package.json
  packages/mds-db/migration.ts
  packages/mds-db/package.json
  packages/mds-logger/package.json
  packages/mds-metrics-sheet/package.json
  packages/mds-native/package.json
  packages/mds-policy-author/package.json
  packages/mds-policy/package.json
  packages/mds-provider/package.json
  packages/mds-providers/package.json
  packages/mds-stream/package.json
  packages/mds-test-data/package.json
  packages/mds-types/package.json
  packages/mds-utils/package.json
Labels: size/L

#36 ALTER TABLE RENAME COLUMN ... TO ...
  packages/mds-db/migration.ts
Labels: size/XS

#29 Upgrade dependencies
  package.json
  packages/mds-cache/package.json
  packages/mds-compliance/package.json
  packages/mds-provider/package.json
  packages/mds-stream/package.json
  yarn.lock
Labels: size/XL

#38 remove letsencrypt option - never worked reliably and not the ingress…
  helm/mds/templates/ingress.yaml
  helm/mds/values.yaml
Labels: size/S

#37 Feature/alex/multi env kubernetes
  helm/mds/templates/ingress.yaml
  helm/mds/values.yaml
Labels: size/XS

#32 Bugfix/alex/virtualservice prefix match
  helm/mds/templates/ingress.yaml
Labels: size/XS

#43 Add standard API request logging
  package.json
  packages/mds-api-server/index.ts
  packages/mds-api-server/package.json
  packages/mds-audit/api.ts
  packages/mds-native/api.ts
  packages/mds-provider/api.ts
  packages/mds-provider/tests/test.ts
  yarn.lock
Labels: size/L

#45 [helm] bugfix - multi env kubernetes
  helm/mds/templates/ingress.yaml
Labels: size/XS

#48 need to quote domains in case of a wildcard globa ("*")
  helm/mds/templates/ingress.yaml
Labels: size/XS
