Repository lacuna-tech/mds-core, pull requests merged in 2019-11, with the labels that each got.

#51 [mds-cache] Remove unused cache methods.
  packages/mds-cache/index.ts
Labels: size/M

#44 [helm] refactor api values and secrets
  bin/mdsctl
  helm/mds/Chart.yaml
  helm/mds/templates/deployment.yaml
  helm/mds/templates/ingress.yaml
  helm/mds/templates/service.yaml
  helm/mds/values.yaml
  helm/mds/values.yaml.tpl
Labels: size/L

#52 docker-compose
  .gitignore
  bin/mdsctl
  docker-compose.yml.tpl
  nginx/Dockerfile
  nginx/nginx.conf
Labels: size/L

#50 fluentbit (mds/requirements rm, util/values pin to es host)
  helm/mds/requirements.lock
  helm/mds/requirements.yaml
  helm/mds/templates/egress.yaml
  helm/mds/values.yaml
  helm/util/values.yaml
Labels: size/M

#33 [mds-db] Populate publish_date on geographies.
  packages/mds-db/geographies.ts
  packages/mds-db/migration.ts
  packages/mds-db/policies.ts
  packages/mds-db/schema.ts
  packages/mds-db/tests/mds-db.spec.ts
  packages/mds-db/types.ts
  packages/mds-types/index.ts
Labels: size/M

#53 [mds-daily] Add perf logging to MDS Daily db/cache calls
  packages/mds-daily/api.ts
  packages/mds-daily/db-helpers.ts
  packages/mds-daily/request-handlers.ts
Labels: size/M

#58 Add provider_id to API logs
  packages/mds-api-server/index.ts
Labels: size/M

#57 please leave downloaded helm charts in place
  package.json
Labels: size/XS

#60 [mds-daily] Break up last day stats by provider endpoint
  packages/mds-daily/api.ts
  packages/mds-daily/request-handlers.ts
Labels: size/L

#59 Feature/jwtodd mdsclt cleanup
  bin/mdsctl
Labels: size/S

#64 [mds-*] Rename carshare back to car to match spec properly
  packages/mds-agency/tests/request-handlers.ts
  packages/mds-types/index.ts
Labels: size/XS

#67 [mdsctl] fix - values.yaml not .html
  bin/mdsctl
Labels: size/XS

#68 simulator needs to access mds-agency:4000 vs 4001
  bin/mdsctl
Labels: size/S

#66 [mds-metrics] First pass at implementing the Metrics API
  .vscode/launch.json
  container-images/mds-metrics/Dockerfile
  container-images/mds-metrics/index.ts
  container-images/mds-metrics/package.json
  container-images/mds-metrics/tsconfig.build.json
  container-images/mds-metrics/webpack.config.js
  docker-compose.yml.tpl
  helm/mds/values.yaml
  helm/mds/values.yaml.tpl
  packages/mds-db/events.ts
  packages/mds-db/types.ts
  packages/mds-metrics/api.ts
  packages/mds-metrics/index.ts
  packages/mds-metrics/package.json
  packages/mds-metrics/request-handlers.ts
  packages/mds-metrics/server.ts
  packages/mds-metrics/tests/request-handlers.test.ts
  packages/mds-metrics/tests/test.ts
  packages/mds-metrics/tsconfig.build.json
  packages/mds-metrics/types.ts
  packages/mds-metrics/utils.ts
Labels: size/XL

#61 [mds-core] Onboarding Improvements
  README.md
  cypress/integration/agency.spec.js
Labels: size/S

#62 MDSAAS-361 TypeScript 3.7
  package.json
  packages/mds-agency/api.ts
  packages/mds-agency/tests/request-handlers.ts
  packages/mds-agency/tests/sandbox-admin-request-handlers.ts
  packages/mds-agency/types.ts
  packages/mds-api-server/index.ts
  packages/mds-audit/api.ts
  packages/mds-audit/service.ts
  packages/mds-audit/tests/api.spec.ts
  packages/mds-audit/types.ts
  packages/mds-cache/index.ts
  packages/mds-compliance/api.ts
  packages/mds-daily/api.ts
  packages/mds-daily/tests/request-handlers.test.ts
  packages/mds-daily/types.ts
  packages/mds-logger/package.json
  packages/mds-metrics-sheet/package.json
  packages/mds-metrics/api.ts
  packages/mds-native/types.ts
  packages/mds-provider/api.ts
  packages/mds-types/index.ts
  yarn.lock
Labels: size/XXL

#63 [mds-daily] [mds-db] [mds-cache] Cache latest event per provider
  packages/mds-cache/index.ts
  packages/mds-daily/db-helpers.ts
  packages/mds-daily/tests/db-helpers.test.ts
Labels: size/M

#70 [mds-metrics] Fix binning bug
  packages/mds-metrics/request-handlers.ts
  packages/mds-metrics/tests/test.ts
  packages/mds-metrics/types.ts
  packages/mds-metrics/utils.ts
  packages/mds-types/index.ts
Labels: size/L

#73 [mds-metrics] Add some more logs for the Metrics API prototype
  packages/mds-metrics/request-handlers.ts
Labels: size/S

#74 [mds-db] Fix `editGeography`
  packages/mds-db/geographies.ts
  packages/mds-db/tests/mds-db.spec.ts
Labels: size/S

#77 [mds-agency] Fix bad event missing timestamp error message
  packages/mds-agency/utils.ts
Labels: size/XS

#75 mdscl/istio: install (un)install via helm straight up
  bin/mdsctl
Labels: size/S

#76 [mds-audit] Support attaching media to audits
  container-images/mds-audit/Dockerfile
  container-images/webpack.config.js
  packages/mds-audit/api.ts
  packages/mds-audit/attachments.ts
  packages/mds-audit/package.json
  packages/mds-audit/tests/api.spec.ts
  packages/mds-audit/tests/attachments.spec.ts
  packages/mds-audit/tests/empty.png
  packages/mds-audit/tests/sample.gif
  packages/mds-audit/tests/sample.png
  packages/mds-audit/tests/samplepng
  packages/mds-audit/tests/samplepng.
  packages/mds-db/attachments.ts
  packages/mds-db/index.ts
  packages/mds-db/schema.ts
  packages/mds-types/index.ts
  packages/mds-utils/exceptions.ts
  yarn.lock
Labels: size/XXL

#42 [mds-audit] Include initial provider state with audits returned via API
  packages/mds-audit/api.ts
  packages/mds-audit/tests/api.spec.ts
  packages/mds-db/events.ts
  packages/mds-db/migration.ts
  packages/mds-db/schema.ts
  packages/mds-native/tests/api.spec.ts
  packages/mds-types/index.ts
Labels: size/L

#49 [mds-db] Backend method for finding policies that use particular geographies.
  packages/mds-db/index.ts
  packages/mds-db/policies.ts
  packages/mds-db/tests/mds-db.spec.ts
Labels: size/S

#71 [mds-logger] Overloading log with log level parameter to support ternary conditions & fluent syntax
  packages/mds-logger/index.ts
  packages/mds-logger/tests/test.ts
Labels: size/M

#80 [mds-cache] Add more granular readAllEvents performance logging
  packages/mds-cache/index.ts
Labels: size/S

#78 [mds-schema-validators] Pull all JSON Schema-related definitions and code into a new package.
  packages/mds-audit/api.ts
  packages/mds-audit/package.json
  packages/mds-audit/tsconfig.build.json
  packages/mds-cache/unflatteners.ts
  packages/mds-compliance/mds-compliance-cli.ts
  packages/mds-compliance/package.json
  packages/mds-compliance/test_data/policies.json
  packages/mds-compliance/tests/engine-test.spec.ts
  packages/mds-compliance/tsconfig.build.json
  packages/mds-compliance/validators.ts
  packages/mds-db/migration.ts
  packages/mds-db/schema.ts
  packages/mds-native/api.ts
  packages/mds-native/package.json
  packages/mds-native/tsconfig.build.json
  packages/mds-policy-author/api.ts
  packages/mds-policy-author/package.json
  packages/mds-policy-author/tsconfig.build.json
  packages/mds-policy/api.ts
  packages/mds-policy/package.json
  packages/mds-policy/tsconfig.build.json
  packages/mds-schema-validators/index.ts
  packages/mds-schema-validators/package.json
  packages/mds-schema-validators/tests/validators.spec.ts
  packages/mds-schema-validators/tsconfig.build.json
  packages/mds-schema-validators/validators.ts
  packages/mds-types/index.ts
  packages/mds-utils/index.ts
  packages/mds-utils/package.json
Labels: size/XL
