Repository lacuna-tech/mds-core, pull requests merged in 2021-12, with the labels that each got.

#829 Build string handling into the DeadLetterSink type
  .changeset/old-timers-smoke.md
  packages/mds-stream-processor/@types/index.ts
  packages/mds-stream-processor/index.ts
Labels: bulldozer-update, bulldozer-merge

#825 Implement way to filter hidden geographies.
  .changeset/rare-geckos-punch.md
  packages/mds-geography-service/@types/index.ts
  packages/mds-geography-service/repository/index.ts
  packages/mds-geography-service/tests/index.spec.ts
Labels: bulldozer-update, bulldozer-merge

#834 [PLAT-306] Add violating_vehicles list to Compliance Snapshots
  .changeset/tender-starfishes-deliver.md
  packages/mds-compliance-api/tests/fixtures.ts
  packages/mds-compliance-engine/@types/index.ts
  packages/mds-compliance-engine/engine/count_processors.ts
  packages/mds-compliance-engine/engine/mds-compliance-engine.ts
  packages/mds-compliance-engine/engine/speed_processors.ts
  packages/mds-compliance-engine/engine/time_processors.ts
  packages/mds-compliance-service/@types/index.ts
  packages/mds-compliance-service/repository/entities/compliance-snapshot-entity.ts
  packages/mds-compliance-service/repository/migrations/1638812382755-AddViolatingVehiclesColumn.ts
  packages/mds-compliance-service/repository/migrations/index.ts
  packages/mds-compliance-service/tests/fixtures.ts
Labels: bulldozer-update, bulldozer-merge

#836 Fix TukTuk provider_id
  .changeset/rare-lizards-cheer.md
  packages/mds-providers/index.ts
Labels: bug, bulldozer-update, bulldozer-merge

#838 Fix geography author api rename
  .changeset/giant-pens-relax.md
  container-images/mds-geography-author-api/package.json
  packages/mds-geography-author-api/package.json
  pnpm-lock.yaml
Labels: bug, bulldozer-update, bulldozer-merge

#840 Remove select on geography hidden filter.
  .changeset/large-pears-end.md
  packages/mds-geography-service/repository/index.ts
  packages/mds-geography-service/tests/index.spec.ts
Labels: bulldozer-update, bulldozer-merge

#841 [mds-types] Improve documentation for utility types
  .changeset/sour-bottles-sell.md
  packages/mds-types/utils.ts
Labels: documentation, bulldozer-update, bulldozer-merge

#842 [mds-compliance-service] Don't write violating_vehicles to kafka
  .changeset/slow-melons-decide.md
  packages/mds-compliance-service/service/provider.ts
  packages/mds-compliance-service/service/stream.ts
  packages/mds-compliance-service/tests/index.spec.ts
Labels: bug, bulldozer-update, bulldozer-merge

#846 [PLAT-304] Rename mds-policy-author -> mds-policy-author-api
  .changeset/late-papayas-hang.md
  .changeset/smart-lions-joke.md
  .vscode/launch.json
  README.md
  container-images/mds-policy-author-api/CHANGELOG.md
  container-images/mds-policy-author-api/Dockerfile
  container-images/mds-policy-author-api/package.json
  container-images/mds-policy-author-api/tsconfig.eslint.json
  container-images/mds-policy-author-api/webpack.config.ts
  container-images/mds-policy-author/webpack.config.ts
  helm/mds/values.yaml
  packages/mds-policy-author-api/CHANGELOG.md
  packages/mds-policy-author-api/LICENSE
  packages/mds-policy-author-api/README.md
  packages/mds-policy-author-api/api.ts
  packages/mds-policy-author-api/handlers/delete-policy.ts
  packages/mds-policy-author-api/handlers/get-bulk-policy-metadata.ts
  packages/mds-policy-author-api/handlers/get-policy-metadata.ts
  packages/mds-policy-author-api/handlers/publish-policy.ts
  packages/mds-policy-author-api/handlers/update-policy-metadata.ts
  packages/mds-policy-author-api/handlers/update-policy.ts
  packages/mds-policy-author-api/handlers/write-policy.ts
  packages/mds-policy-author-api/index.ts
  packages/mds-policy-author-api/jest.config.js
  packages/mds-policy-author-api/logger.ts
  packages/mds-policy-author-api/middleware.ts
  packages/mds-policy-author-api/package.json
  packages/mds-policy-author-api/policy-author-api-version.ts
  packages/mds-policy-author-api/server.ts
  packages/mds-policy-author-api/tests/api.spec.ts
  packages/mds-policy-author-api/tsconfig.build.json
  packages/mds-policy-author-api/types.ts
  packages/mds-policy-author/logger.ts
  packages/mds-policy-service/CHANGELOG.md
  packages/mds-policy-service/README.md
  pnpm-lock.yaml
  values.yaml.tpl
Labels: bulldozer-update

#847 Fix compliance_as_of to be consistent for a given batch process execution
  .changeset/tidy-squids-grow.md
  .changeset/weak-kangaroos-notice.md
  packages/mds-compliance-batch-processor/batch_process.ts
  packages/mds-compliance-engine/engine/mds-compliance-engine.ts
Labels: bug, bulldozer-update, bulldozer-merge

#848 Export test helpers from mds-geography-service, switch imports in other packages to using a real package as opposed to an obscured submodule
  .changeset/rotten-zebras-confess.md
  .changeset/sharp-parrots-jam.md
  packages/mds-geography-api/tests/index.spec.ts
  packages/mds-geography-service/index.ts
  packages/mds-policy-author-api/tests/api.spec.ts
  packages/mds-policy-service/tests/helpers.ts
  packages/mds-policy-service/tests/policy-client.spec.ts
Labels: bug, bulldozer-update, bulldozer-merge

#860 [PLAT-323] Abort ProcessManager retries on failure once the ProcessManager has been stopped
  .changeset/smart-years-compare.md
  packages/mds-service-helpers/server/index.ts
Labels: bug, bulldozer-update, bulldozer-merge
