Repository lacuna-tech/mds-core, pull requests merged in 2021-09, with the labels that each got.

#712 [PLAT-119] Initialize cache prior to migration by paging through all devices
  .changeset/gorgeous-impalas-attend.md
  .changeset/seven-lemons-warn.md
  packages/mds-ingest-migration-processor/processor.ts
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/client/index.ts
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/service/manager.ts
  packages/mds-ingest-service/service/provider.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-ingest-service/tests/index.spec.ts
Labels: bulldozer-update, bulldozer-merge

#715 Add missing TypeORM model decorators and add a migration to sync schema
  .changeset/chilly-mugs-bake.md
  packages/mds-ingest-service/repository/entities/event-annotation-entity.ts
  packages/mds-ingest-service/repository/entities/event-entity.ts
  packages/mds-ingest-service/repository/migrations/1630418242374-SetEventAnnotationsEventsRowIdColumnNotNull.ts
  packages/mds-ingest-service/repository/migrations/index.ts
Labels: bulldozer-update

#718 [PLAT-117] Refactor telemetry caching to remove redundant code and other misc fixes
  .changeset/curly-files-doubt.md
  .changeset/new-moles-leave.md
  .changeset/silver-spies-fail.md
  packages/mds-agency-cache/index.ts
  packages/mds-ingest-migration-processor/processor.ts
  packages/mds-logger/tests/index.spec.ts
Labels: bulldozer-update

#720 [PLAT-112] Use pnpm workspace protocol for @mds-core packages
  container-images/mds-agency/package.json
  container-images/mds-attachment-service/package.json
  container-images/mds-audit-service/package.json
  container-images/mds-audit/package.json
  container-images/mds-collector-api/package.json
  container-images/mds-collector-backend/package.json
  container-images/mds-compliance-api/package.json
  container-images/mds-compliance-service/package.json
  container-images/mds-geography-author/package.json
  container-images/mds-geography-service/package.json
  container-images/mds-geography/package.json
  container-images/mds-ingest-migration-processor/package.json
  container-images/mds-ingest-service/package.json
  container-images/mds-jurisdiction-service/package.json
  container-images/mds-jurisdiction/package.json
  container-images/mds-policy-author/package.json
  container-images/mds-policy-service/package.json
  container-images/mds-policy/package.json
  container-images/mds-transaction-api/package.json
  container-images/mds-transaction-service/package.json
  packages/mds-agency-cache/package.json
  packages/mds-agency/package.json
  packages/mds-api-authorizer/package.json
  packages/mds-api-helpers/package.json
  packages/mds-api-server/package.json
  packages/mds-attachment-service/package.json
  packages/mds-audit-service/package.json
  packages/mds-audit/package.json
  packages/mds-cache/package.json
  packages/mds-collector-api/package.json
  packages/mds-collector-backend/package.json
  packages/mds-compliance-api/package.json
  packages/mds-compliance-engine/package.json
  packages/mds-compliance-service/package.json
  packages/mds-db/package.json
  packages/mds-geography-author/package.json
  packages/mds-geography-service/package.json
  packages/mds-geography/package.json
  packages/mds-ingest-migration-processor/package.json
  packages/mds-ingest-service/package.json
  packages/mds-jurisdiction-service/package.json
  packages/mds-jurisdiction/package.json
  packages/mds-policy-author/package.json
  packages/mds-policy-service/package.json
  packages/mds-policy/package.json
  packages/mds-providers/package.json
  packages/mds-repository/package.json
  packages/mds-rpc-common/package.json
  packages/mds-schema-validators/package.json
  packages/mds-service-helpers/package.json
  packages/mds-stream-processor/package.json
  packages/mds-stream/package.json
  packages/mds-test-data/package.json
  packages/mds-transaction-api/package.json
  packages/mds-transaction-service/package.json
  packages/mds-utils/package.json
  pnpm-lock.yaml
Labels: bulldozer-update, bulldozer-merge

#724 Ingest migration processor updates
  .changeset/honest-wolves-leave.md
  .changeset/sweet-coins-applaud.md
  packages/mds-api-server/middleware/request-logging.ts
  packages/mds-ingest-migration-processor/package.json
  packages/mds-ingest-migration-processor/processor.ts
  packages/mds-ingest-migration-processor/tsconfig.build.json
  packages/mds-ingest-service/repository/migrations/1631275864436-IncreaseMigratedFromSourceColumnLength.ts
  packages/mds-ingest-service/repository/migrations/index.ts
  packages/mds-ingest-service/repository/mixins/migrated-entity.ts
  packages/mds-rpc-common/server/index.ts
  pnpm-lock.yaml
Labels: bulldozer-update, bulldozer-merge

#726 Event annotations require the original event id
  .changeset/curly-vans-confess.md
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/repository/mappers/event-mappers.ts
  packages/mds-ingest-service/service/provider.ts
Labels: bulldozer-update, bulldozer-merge

#725 Make remote address logging optional
  .changeset/polite-rivers-kick.md
  packages/mds-api-server/middleware/request-logging.ts
  packages/mds-rpc-common/server/index.ts
Labels: bulldozer-update, bulldozer-merge

#730 Tiny mds-compliance-api spec bugfix
  packages/mds-compliance-api/spec/flat-spec.json
  packages/mds-compliance-api/spec/spec.yaml
Labels: bulldozer-update, bulldozer-merge

#740 Update policy status filter queries.
  .changeset/eleven-moles-smoke.md
  packages/mds-policy-service/repository/index.ts
Labels: bulldozer-update, bulldozer-merge

#731 PLAT-113 Remove All Joy from MDS-Core
  .changeset/seven-schools-provide.md
  .changeset/slimy-cars-jam.md
  packages/mds-agency/request-handlers.ts
  packages/mds-agency/tests/integration-tests.spec.ts
  packages/mds-attachment-service/service/validators.ts
  packages/mds-audit-service/service/validators.ts
  packages/mds-audit/api.ts
  packages/mds-audit/package.json
  packages/mds-audit/tests/api.spec.ts
  packages/mds-audit/tsconfig.build.json
  packages/mds-audit/types.ts
  packages/mds-audit/validators.ts
  packages/mds-compliance-service/package.json
  packages/mds-compliance-service/service/provider.ts
  packages/mds-compliance-service/service/validators.ts
  packages/mds-compliance-service/tests/index.spec.ts
  packages/mds-geography-author/api.ts
  packages/mds-geography-author/tests/api.spec.ts
  packages/mds-geography-author/validators.ts
  packages/mds-geography-service/package.json
  packages/mds-geography-service/service/validators.ts
  packages/mds-geography-service/tests/index.spec.ts
  packages/mds-jurisdiction-service/service/validators.ts
  packages/mds-jurisdiction-service/tests/index.spec.ts
  packages/mds-schema-validators/index.ts
  packages/mds-schema-validators/package.json
  packages/mds-schema-validators/trip-metadata-validators.ts
  packages/mds-schema-validators/validators.ts
  packages/mds-transaction-service/repository/index.ts
  packages/mds-transaction-service/service/validators.ts
  pnpm-lock.yaml
Labels: bulldozer-merge
