Repository lacuna-tech/mds-core, pull requests merged in 2021-07, with the labels that each got.

#643 [mds-ingest-service] Add pagination and order support to getEvents via ingest
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/client/index.ts
  packages/mds-ingest-service/package.json
  packages/mds-ingest-service/repository/entities/event-entity.ts
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/service/manager.ts
  packages/mds-ingest-service/service/provider.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-ingest-service/tests/index.spec.ts
  pnpm-lock.yaml
Labels: bulldozer-merge

#642 Add support for mset to mds-cache
  packages/mds-cache/redis/index.ts
  packages/mds-cache/tests/redis.spec.ts
Labels: bulldozer-merge, bulldozer-update

#641 [mds-agency] Switch event validation to AJV
  .eslintrc.json
  packages/mds-agency/api.ts
  packages/mds-agency/handlers/create-event.ts
  packages/mds-agency/request-handlers.ts
  packages/mds-agency/tests/integration-tests.spec.ts
  packages/mds-agency/types.ts
  packages/mds-agency/utils.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-types/utils.ts
Labels: tech-debt

#648 fixes all_events query to use start/end, adds missing indicies
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/repository/migrations/1603212540962-CreateEventsTable.ts
  packages/mds-ingest-service/repository/migrations/1625676583247-AddEventsTripIdTimestampIndex.ts
  packages/mds-ingest-service/tests/index.spec.ts
Labels: bulldozer-merge, bulldozer-update

#645 Initial ingest service refactor for 0.4 to 1.0 upgrade
  packages/mds-ingest-service/repository/entities/device-entity.ts
  packages/mds-ingest-service/repository/entities/event-entity.ts
  packages/mds-ingest-service/repository/entities/telemetry-entity.ts
  packages/mds-ingest-service/repository/mappers/device-mappers.ts
  packages/mds-ingest-service/repository/mappers/event-mappers.ts
  packages/mds-ingest-service/repository/mappers/telemetry-mappers.ts
  packages/mds-ingest-service/repository/migrations/1625241719659-CreateMigrationColumns.ts
  packages/mds-ingest-service/repository/migrations/index.ts
  packages/mds-ingest-service/repository/mixins/migrated-entity.ts
Labels: bulldozer-merge

#647 Update typeorm peer dependency version
  packages/mds-repository/package.json
Labels: bulldozer-merge, bulldozer-update

#640 New mds-ingest-service method to writeEventAnnotations
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/client/index.ts
  packages/mds-ingest-service/repository/entities/event-annotation-entity.ts
  packages/mds-ingest-service/repository/entities/index.ts
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/repository/mappers/event-annotation-mappers.ts
  packages/mds-ingest-service/repository/mappers/index.ts
  packages/mds-ingest-service/repository/migrations/1624574823000-AddEventAnnotationEntity.ts
  packages/mds-ingest-service/repository/migrations/index.ts
  packages/mds-ingest-service/service/manager.ts
  packages/mds-ingest-service/service/provider.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-ingest-service/tests/index.spec.ts
Labels: bulldozer-merge, bulldozer-update

#649 Address some comments from PR #640
  packages/mds-ingest-service/repository/entities/event-annotation-entity.ts
  packages/mds-ingest-service/service/validators.ts
Labels: bulldozer-merge, bulldozer-update

#650 [mds-ingest-service] Add missing migration to migrations/index.ts
  packages/mds-ingest-service/repository/migrations/1625676583247-AddEventsTripIdTimestampIndex.ts
  packages/mds-ingest-service/repository/migrations/index.ts
Labels: bulldozer-merge, bulldozer-update

#653 Run eslint on spec/test files
  package.json
  packages/mds-agency/jest-tests/taxi-tests.jest.spec.ts
  packages/mds-agency/jest.config.js
  packages/mds-agency/tests/request-handlers.spec.ts
  packages/mds-agency/tests/sandbox-admin-request-handlers.spec.ts
  packages/mds-api-authorizer/tests/index.spec.ts
  packages/mds-api-helpers/tests/index.spec.ts
  packages/mds-api-server/tests/index.spec.ts
  packages/mds-attachment-service/jest.config.js
  packages/mds-attachment-service/tests/index.spec.ts
  packages/mds-audit-service/jest.config.js
  packages/mds-audit-service/tests/index.spec.ts
  packages/mds-audit/tests/api.spec.ts
  packages/mds-audit/tests/attachments.spec.ts
  packages/mds-cache/jest.config.js
  packages/mds-collector-api/jest.config.js
  packages/mds-collector-api/tests/api.spec.ts
  packages/mds-collector-backend/jest.config.js
  packages/mds-collector-backend/tests/service.spec.ts
  packages/mds-compliance-api/jest.config.js
  packages/mds-compliance-api/tests/index.spec.ts
  packages/mds-compliance-engine/tests/engine/count-tests.spec.ts
  packages/mds-compliance-engine/tests/engine/engine-test.spec.ts
  packages/mds-compliance-engine/tests/engine/speed-tests.spec.ts
  packages/mds-compliance-engine/tests/engine/time-tests.spec.ts
  packages/mds-compliance-service/jest.config.js
  packages/mds-compliance-service/tests/index.spec.ts
  packages/mds-db/tests/mds-db.spec.ts
  packages/mds-db/tests/policies.spec.ts
  packages/mds-geography-author/tests/api.spec.ts
  packages/mds-geography-service/jest.config.js
  packages/mds-geography-service/tests/index.spec.ts
  packages/mds-geography/tests/api.spec.ts
  packages/mds-ingest-service/jest.config.js
  packages/mds-jurisdiction-service/jest.config.js
  packages/mds-jurisdiction-service/tests/index.spec.ts
  packages/mds-jurisdiction/tests/api.spec.ts
  packages/mds-policy-author/tests/api.spec.ts
  packages/mds-policy-service/jest.config.js
  packages/mds-policy-service/tests/index.spec.ts
  packages/mds-policy/tests/api.spec.ts
  packages/mds-repository/tests/filters.spec.ts
  packages/mds-rpc-common/tests/index.spec.ts
  packages/mds-schema-validators/jest.config.js
  packages/mds-schema-validators/tests/validators.spec.ts
  packages/mds-service-helpers/tests/index.spec.ts
  packages/mds-stream/jest.config.js
  packages/mds-transaction-api/jest.config.js
  packages/mds-transaction-api/tests/transaction-operations.spec.ts
  packages/mds-transaction-api/tests/transaction-statuses.spec.ts
  packages/mds-transaction-api/tests/transactions.spec.ts
  packages/mds-transaction-service/jest.config.js
  packages/mds-transaction-service/tests/transaction-operations.spec.ts
  packages/mds-transaction-service/tests/transaction-statuses.spec.ts
  packages/mds-transaction-service/tests/transactions.spec.ts
  packages/mds-types/tests/index.spec.ts
  packages/mds-utils/tests/utils.spec.ts
Labels: bulldozer-update

#652 [LCORE-274] Add stream processor types/utilities to mds-core
  packages/mds-stream-processor/@types/index.ts
  packages/mds-stream-processor/connectors/console-connector.ts
  packages/mds-stream-processor/connectors/file-connector.ts
  packages/mds-stream-processor/connectors/generator-connector.ts
  packages/mds-stream-processor/connectors/index.ts
  packages/mds-stream-processor/connectors/kafka-connector.ts
  packages/mds-stream-processor/index.ts
  packages/mds-stream-processor/jest.config.js
  packages/mds-stream-processor/package.json
  packages/mds-stream-processor/tsconfig.build.json
  pnpm-lock.yaml
Labels: bulldozer-update

#661 rework Paginator.paginate, to work well
  .changeset/young-parrots-occur.md
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/repository/migrations/1627315083728-AddEventsTimestampIdIndex.ts
  packages/mds-ingest-service/repository/migrations/1627315276644-AddEventsProviderIdIdIndex.ts
  packages/mds-ingest-service/repository/migrations/1627315357677-AddEventsVehicleStateIdIndex.ts
  packages/mds-ingest-service/repository/migrations/index.ts
Labels: bulldozer-update

#671 Fix test runner to actually run sequentially
  Jenkinsfile
Labels: bulldozer-update

#654 MDS Ingest Data Migration Processor
  .changeset/nine-deers-laugh.md
  container-images/mds-ingest-migration-processor/Dockerfile
  container-images/mds-ingest-migration-processor/package.json
  container-images/mds-ingest-migration-processor/webpack.config.ts
  packages/mds-ingest-migration-processor/index.ts
  packages/mds-ingest-migration-processor/package.json
  packages/mds-ingest-migration-processor/processor.ts
  packages/mds-ingest-migration-processor/tsconfig.build.json
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/client/index.ts
  packages/mds-ingest-service/repository/entities/event-entity.ts
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/repository/mappers/device-mappers.ts
  packages/mds-ingest-service/repository/mappers/event-mappers.ts
  packages/mds-ingest-service/repository/mappers/telemetry-mappers.ts
  packages/mds-ingest-service/service/manager.ts
  packages/mds-ingest-service/service/provider.ts
  packages/mds-ingest-service/tests/index.spec.ts
  packages/mds-types/telemetry.ts
  pnpm-lock.yaml
Labels: bulldozer-update
