Repository lacuna-tech/mds-core, pull requests merged in 2021-06, with the labels that each got.

#625 Allow randomElement function to operate on const arrays
  package.json
  packages/mds-utils/utils.ts
Labels: bulldozer-merge, bulldozer-update

#626 Ignore advisory 1753 from Lerna
  package.json
Labels: bulldozer-merge, bulldozer-update

#631 Fix error handling middleware in bundled (minified) images.
  packages/mds-api-server/middleware/api-error-handling.ts
  packages/mds-service-helpers/client/index.ts
Labels: bulldozer-merge, bulldozer-update

#632 Data pipeline needs trip metadata recorded property for watermarking.
  packages/mds-agency/request-handlers.ts
Labels: bulldozer-update

#633 [mds-agency] Remove TripMetadata cache writes
  packages/mds-agency-cache/index.ts
  packages/mds-agency/request-handlers.ts
Labels: bulldozer-merge, bulldozer-update

#613 MDS-ingest-service - Get Events Query
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/client/index.ts
  packages/mds-ingest-service/package.json
  packages/mds-ingest-service/repository/entities/event-entity.ts
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/repository/mappers/event-mappers.ts
  packages/mds-ingest-service/repository/migrations/1603212540962-CreateEventsTable.ts
  packages/mds-ingest-service/service/manager.ts
  packages/mds-ingest-service/service/provider.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-ingest-service/tests/index.spec.ts
  packages/mds-ingest-service/tsconfig.build.json
  packages/mds-types/event.ts
  packages/mds-types/vehicle/vehicle_states.ts
  pnpm-lock.yaml
Labels: bulldozer-update

#634 [mds-agency] Switch Device validation to AJV
  packages/mds-agency/package.json
  packages/mds-agency/request-handlers.ts
  packages/mds-agency/tests/integration-tests.spec.ts
  packages/mds-agency/types.ts
  packages/mds-agency/utils.ts
  packages/mds-db/devices.ts
  packages/mds-ingest-service/index.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-types/device.ts
  pnpm-lock.yaml
Labels: bulldozer-merge, bulldozer-update

#639 [mds-agency] Switch Telemetry Validation to AJV, fix spec discontinuities
  .prettierrc.json
  package.json
  packages/mds-agency/api.ts
  packages/mds-agency/handlers/create-telemetry.ts
  packages/mds-agency/request-handlers.ts
  packages/mds-agency/tests/integration-tests.spec.ts
  packages/mds-agency/types.ts
  packages/mds-agency/utils.ts
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/repository/entities/telemetry-entity.ts
  packages/mds-ingest-service/repository/mappers/telemetry-mappers.ts
  packages/mds-ingest-service/repository/migrations/1624574421590-AddTelemetryStopIdHdopSatellitesColumns.ts
  packages/mds-ingest-service/repository/migrations/index.ts
  packages/mds-ingest-service/service/validators.ts
  packages/mds-ingest-service/tests/index.spec.ts
  packages/mds-types/telemetry.ts
  pnpm-lock.yaml
Labels: tech-debt
