Repository lacuna-tech/mds-core, pull requests merged in 2022-03, with the labels that each got.

#919 Allow JSON Schema Draft-7 date format in SchemaValidator
  .changeset/thick-spies-bake.md
  packages/mds-schema-validators/index.ts
Labels: enhancement, bulldozer-update, bulldozer-merge

#917 Allow floating point numbers for trip distance
  .changeset/smart-moons-care.md
  packages/mds-transaction-api/schema-gen/TransactionSchema.json
  packages/mds-transaction-api/spec/flat-spec.json
  packages/mds-transaction-service/service/validators.ts
Labels: bug, bulldozer-update, bulldozer-merge

#918 Delete all remaining references to Joi
  .changeset/perfect-games-bake.md
  packages/mds-attachment-service/package.json
  packages/mds-audit-service/package.json
  packages/mds-compliance-api/package.json
  packages/mds-compliance-engine/mds-compliance-cli.ts
  packages/mds-geography-service/package.json
  packages/mds-ingest-service/package.json
  packages/mds-policy-service/package.json
  packages/mds-schema-validators/index.ts
  packages/mds-schema-validators/jest.config.js
  packages/mds-schema-validators/package.json
  packages/mds-schema-validators/tests/validators.spec.ts
  packages/mds-schema-validators/v0_4_1/index.ts
  packages/mds-schema-validators/validators.ts
  packages/mds-transaction-api/package.json
  packages/mds-transaction-service/package.json
  pnpm-lock.yaml
Labels: tech-debt, bulldozer-update, bulldozer-merge

#916 Cache node_modules between action runs, run on any pull requests targeting develop branch
  .github/workflows/run-tests.yaml
Labels: enhancement, bulldozer-update, bulldozer-merge

#922 Fix mds-policy build error that was somehow only being surfaced when running pnpm image
  .changeset/real-bees-return.md
  packages/mds-policy/handlers/get-policy.ts
Labels: bug, bulldozer-update, bulldozer-merge

#927 [PLAT-396] [PLAT-415] Add additional Taxi Co's to mds-providers
  .changeset/ten-lizards-promise.md
  packages/mds-providers/index.ts
Labels: enhancement, bulldozer-update, bulldozer-merge

#931 [PLAT-398] Move .swcrc
  .jest/.swcrc
  .jest/jest.config.js
Labels: bulldozer-update, bulldozer-merge

#932 Upgrade @typescript-eslint for TypeScript 4.6
  package.json
  pnpm-lock.yaml
Labels: bulldozer-update

#933 [PLAT-420] Bump swc dependencies
  package.json
  packages/mds-api-helpers/jest.config.js
  pnpm-lock.yaml
Labels: bug, dependencies, bulldozer-update, bulldozer-merge

#938 Optional RpcServiceManager onStart/onStop handlers
  .changeset/lazy-coins-mix.md
  packages/mds-rpc-common/server/index.ts
Labels: bulldozer-update

#940 Some miscellaneous mds-repository updates
  .changeset/brave-cups-grow.md
  .changeset/curly-olives-hide.md
  .changeset/two-beers-thank.md
  packages/mds-config-files/index.ts
  packages/mds-repository/mapper.ts
  packages/mds-repository/repository.ts
Labels: bulldozer-update

#941 removed date-time-utils (unused), refactored tests from mocha to jest
  .changeset/weak-clouds-attend.md
  .vscode/launch.json
  packages/mds-utils/date-time-utils.ts
  packages/mds-utils/jest.config.js
  packages/mds-utils/package.json
  packages/mds-utils/tests/date-time-utils.spec.ts
  packages/mds-utils/tests/deep-pick-properties.spec.ts
  packages/mds-utils/tests/utils.spec.ts
  packages/mds-utils/utils.ts
Labels: bulldozer-update

#942 API Authorizer enhancements to support calling RPC services requiring an authorization context
  .changeset/smooth-seas-dream.md
  packages/mds-api-authorizer/index.ts
  packages/mds-api-authorizer/tests/index.spec.ts
  packages/mds-api-server/@types/index.ts
  packages/mds-api-server/middleware/authorization.ts
  packages/mds-api-server/utils/index.ts
  packages/mds-rpc-common/@types/index.ts
  packages/mds-rpc-common/index.ts
  packages/mds-rpc-common/package.json
  packages/mds-rpc-common/tsconfig.build.json
  pnpm-lock.yaml
Labels: bulldozer-update

#944 Don't require provider_id in audit event telemetry
  .changeset/gentle-dots-glow.md
  packages/mds-audit-api/api.ts
  packages/mds-audit-api/package.json
  packages/mds-audit-api/types.ts
  packages/mds-audit-api/validators.ts
  packages/mds-audit-service/@types/index.ts
  packages/mds-audit-service/index.ts
  packages/mds-audit-service/service/validators.ts
  pnpm-lock.yaml
Labels: bulldozer-update, bulldozer-merge

#951 Await ingest get-device when attempting to write an event
  .changeset/smart-donkeys-film.md
  packages/mds-db/events.ts
Labels: hotfix

#948 Add auto-update action, optimize test action
  .github/workflows/autoupdate.yaml
  .github/workflows/pr-checker.yaml
Labels: auto-update

#950 PLAT-382 mds audit api - convert mocha to jest
  .changeset/khaki-foxes-care.md
  .jest/jest.config.js
  .vscode/launch.json
  packages/mds-audit-api/jest.config.js
  packages/mds-audit-api/package.json
  packages/mds-audit-api/tests/api.spec.ts
  packages/mds-audit-api/tests/attachments.spec.ts
Labels: bulldozer-merge, auto-update

#954 Add rlwrap for improved nc/REPL experience
  container-images/mds-agency/Dockerfile
  container-images/mds-attachment-service/Dockerfile
  container-images/mds-audit-api/Dockerfile
  container-images/mds-audit-service/Dockerfile
  container-images/mds-collector-api/Dockerfile
  container-images/mds-collector-service/Dockerfile
  container-images/mds-compliance-api/Dockerfile
  container-images/mds-compliance-service/Dockerfile
  container-images/mds-config-api/Dockerfile
  container-images/mds-config-service/Dockerfile
  container-images/mds-geography-api/Dockerfile
  container-images/mds-geography-author-api/Dockerfile
  container-images/mds-geography-service/Dockerfile
  container-images/mds-ingest-service/Dockerfile
  container-images/mds-jurisdiction-api/Dockerfile
  container-images/mds-jurisdiction-service/Dockerfile
  container-images/mds-policy-author-api/Dockerfile
  container-images/mds-policy-service/Dockerfile
  container-images/mds-policy/Dockerfile
  container-images/mds-transaction-api/Dockerfile
  container-images/mds-transaction-service/Dockerfile
Labels: auto-update

#955 Run build/test on autoupdate completion
  .github/workflows/pr-checker.yaml
Labels: auto-update

#960 Upgrade to node:16.14.2-alpine3.15 to resolve rlwrap installation bug
  .changeset/real-shirts-obey.md
  .github/workflows/pr-checker.yaml
  .nvmrc
  Jenkinsfile
  container-images/mds-agency/Dockerfile
  container-images/mds-attachment-service/Dockerfile
  container-images/mds-audit-api/Dockerfile
  container-images/mds-audit-service/Dockerfile
  container-images/mds-collector-api/Dockerfile
  container-images/mds-collector-service/Dockerfile
  container-images/mds-compliance-api/Dockerfile
  container-images/mds-compliance-service/Dockerfile
  container-images/mds-config-api/Dockerfile
  container-images/mds-config-service/Dockerfile
  container-images/mds-geography-api/Dockerfile
  container-images/mds-geography-author-api/Dockerfile
  container-images/mds-geography-service/Dockerfile
  container-images/mds-ingest-service/Dockerfile
  container-images/mds-jurisdiction-api/Dockerfile
  container-images/mds-jurisdiction-service/Dockerfile
  container-images/mds-policy-author-api/Dockerfile
  container-images/mds-policy-service/Dockerfile
  container-images/mds-policy/Dockerfile
  container-images/mds-transaction-api/Dockerfile
  container-images/mds-transaction-service/Dockerfile
  okteto.yml
  package.json
Labels: bug, enhancement, dependencies

#963 Allow auth related service exceptions
  .changeset/green-buckets-compete.md
  packages/mds-service-helpers/@types/index.ts
  packages/mds-service-helpers/server/index.ts
Labels: bulldozer-merge

#965 Run tests on any PRs against develop
  .github/workflows/pr-checker.yaml
Labels: bug

#968 Resolve all linter warnings, add a few new linter rules
  .changeset/nine-cougars-think.md
  .eslintrc.json
  package.json
  packages/mds-agency-cache/index.ts
  packages/mds-agency/handlers/create-event.ts
  packages/mds-agency/server.ts
  packages/mds-agency/tests/integration-tests.spec.ts
  packages/mds-agency/tests/request-handlers.spec.ts
  packages/mds-agency/tests/taxi-test-helpers.ts
  packages/mds-agency/types.ts
  packages/mds-agency/utils.ts
  packages/mds-api-server/api-server.ts
  packages/mds-api-server/tests/index.spec.ts
  packages/mds-attachment-service/service/helpers/index.ts
  packages/mds-audit-api/attachments.ts
  packages/mds-audit-api/server.ts
  packages/mds-audit-api/tests/api.spec.ts
  packages/mds-audit-api/tests/attachments.spec.ts
  packages/mds-cache/tests/redis.spec.ts
  packages/mds-collector-service/service/provider.ts
  packages/mds-compliance-batch-processor/exec.ts
  packages/mds-compliance-batch-processor/test_data/batch_fixtures.ts
  packages/mds-compliance-engine/engine/count_processors.ts
  packages/mds-compliance-engine/engine/speed_processors.ts
  packages/mds-compliance-engine/engine/time_processors.ts
  packages/mds-compliance-engine/mds-compliance-cli.ts
  packages/mds-compliance-engine/tests/engine/count-tests.spec.ts
  packages/mds-compliance-engine/tests/engine/speed-tests.spec.ts
  packages/mds-compliance-engine/tests/engine/time-tests.spec.ts
  packages/mds-compliance-service/repository/index.ts
  packages/mds-compliance-service/service/provider.ts
  packages/mds-geography-api/api.ts
  packages/mds-geography-author-api/tests/api.spec.ts
  packages/mds-geography-service/@types/index.ts
  packages/mds-ingest-service/tests/index.spec.ts
  packages/mds-jurisdiction-service/tests/index.spec.ts
  packages/mds-policy-author-api/handlers/get-policy-metadata.ts
  packages/mds-policy-author-api/handlers/update-policy-metadata.ts
  packages/mds-policy-author-api/tests/api.spec.ts
  packages/mds-policy-service/tests/policy-client.spec.ts
  packages/mds-policy-service/tests/policy-repository.spec.ts
  packages/mds-policy/tests/api.spec.ts
  packages/mds-rpc-common/client/index.ts
  packages/mds-schema-validators/generators/flat-spec-generator.ts
  packages/mds-stream-processor/tests/dead-letter.spec.ts
  packages/mds-transaction-api/tests/transaction-operations.spec.ts
  packages/mds-transaction-api/tests/transaction-statuses.spec.ts
  packages/mds-utils/deep-pick-properties.ts
  packages/mds-webpack-config/index.ts
  pnpm-lock.yaml
Labels: enhancement

#972 [PLAT-429] Optimize Dockerfiles for caching
  .changeset/plenty-crews-wink.md
  container-images/mds-agency/Dockerfile
  container-images/mds-attachment-service/Dockerfile
  container-images/mds-audit-api/Dockerfile
  container-images/mds-audit-service/Dockerfile
  container-images/mds-collector-api/Dockerfile
  container-images/mds-collector-service/Dockerfile
  container-images/mds-compliance-api/Dockerfile
  container-images/mds-compliance-service/Dockerfile
  container-images/mds-config-api/Dockerfile
  container-images/mds-config-service/Dockerfile
  container-images/mds-geography-api/Dockerfile
  container-images/mds-geography-author-api/Dockerfile
  container-images/mds-geography-service/Dockerfile
  container-images/mds-ingest-service/Dockerfile
  container-images/mds-jurisdiction-api/Dockerfile
  container-images/mds-jurisdiction-service/Dockerfile
  container-images/mds-policy-author-api/Dockerfile
  container-images/mds-policy-service/Dockerfile
  container-images/mds-policy/Dockerfile
  container-images/mds-transaction-api/Dockerfile
  container-images/mds-transaction-service/Dockerfile
Labels: enhancement, tech-debt
