Repository lacuna-tech/mds-core, pull requests merged in 2022-05, with the labels that each got.

#1012 Add provider service to template yaml
  values.yaml.tpl
Labels: bug

#1014 [FCO-7] Add Provider Seeding from Config, update fallback provider_types for some providers.
  .changeset/clever-maps-relax.md
  packages/mds-provider-service/repository/fallback_providers.ts
  packages/mds-provider-service/repository/index.ts
Labels: enhancement

#1016 [PLAT-524] Add Accessibility Options to Event Annotations
  .changeset/stupid-terms-end.md
  packages/mds-ingest-service/@types/models.ts
  packages/mds-ingest-service/repository/entities/event-annotation-entity.ts
  packages/mds-ingest-service/repository/migrations/1652752567678-AddAccessibilityOptionsColumnToEventAnnotations.ts
  packages/mds-ingest-service/repository/migrations/index.ts
  packages/mds-ingest-service/service/event_validators.ts
  packages/mds-ingest-service/tests/index.spec.ts
  packages/mds-transaction-api/schema-gen/TransactionSchema.json
  packages/mds-transaction-api/spec/flat-spec.json
Labels: enhancement

#1022 Update provider colors in fallback_providers
  .changeset/beige-files-learn.md
  packages/mds-provider-service/repository/fallback_providers.ts
Labels: bulldozer-merge
