Repository lacuna-tech/mds-core, pull requests merged in 2022-02, with the labels that each got.

#877 [PLAT-360] Upgrade to TS 4.5.5
  .changeset/modern-monkeys-guess.md
  .changeset/selfish-cows-whisper.md
  .changeset/tender-snails-care.md
  package.json
  packages/mds-agency-cache/index.ts
  packages/mds-agency/handlers/create-event.ts
  packages/mds-agency/handlers/create-telemetry.ts
  packages/mds-agency/request-handlers.ts
  packages/mds-attachment-service/package.json
  packages/mds-audit-api/api.ts
  packages/mds-audit-api/attachments.ts
  packages/mds-audit-api/package.json
  packages/mds-cache/redis/helpers/client.ts
  packages/mds-collector-service/service/provider.ts
  packages/mds-compliance-api/handlers/get-compliance-snapshot-ids.ts
  packages/mds-compliance-api/handlers/get-violation-details-snapshot.ts
  packages/mds-compliance-api/handlers/get-violation-periods.ts
  packages/mds-db/audits.ts
  packages/mds-db/client.ts
  packages/mds-db/index.ts
  packages/mds-db/telemetry.ts
  packages/mds-db/trips.ts
  packages/mds-geography-api/api.ts
  packages/mds-geography-author-api/handlers/create-geography.ts
  packages/mds-geography-author-api/handlers/delete-geography.ts
  packages/mds-geography-author-api/handlers/get-all-geography-metadata.ts
  packages/mds-geography-author-api/handlers/get-geography-metadata.ts
  packages/mds-geography-author-api/handlers/publish-geography.ts
  packages/mds-geography-author-api/handlers/update-geography-metadata.ts
  packages/mds-geography-author-api/handlers/update-geography.ts
  packages/mds-geography-service/service/validators.ts
  packages/mds-jurisdiction-api/handlers/create-jurisdiction.ts
  packages/mds-jurisdiction-service/tests/index.spec.ts
  packages/mds-policy-author-api/handlers/delete-policy.ts
  packages/mds-policy-author-api/handlers/publish-policy.ts
  packages/mds-policy-service/repository/index.ts
  packages/mds-repository/mapper.ts
  packages/mds-rpc-common/client/index.ts
  packages/mds-rpc-common/server/index.ts
  packages/mds-service-helpers/client/index.ts
  packages/mds-service-helpers/server/index.ts
  packages/mds-stream-processor/index.ts
  packages/mds-stream/index.ts
  packages/mds-stream/kafka/stream-consumer.ts
  packages/mds-stream/kafka/stream-producer.ts
  packages/mds-stream/nats/helpers.ts
  packages/mds-types/utils.ts
  packages/mds-utils/exceptions/exceptions.ts
  packages/mds-utils/state-machine.ts
  pnpm-lock.yaml
Labels: tech-debt, dependencies, bulldozer-update, bulldozer-merge

#878 Minor tweaks to Geography API types & Geography Service
  .changeset/many-dingos-cry.md
  .changeset/shiny-mugs-scream.md
  packages/mds-geography-api/types.ts
  packages/mds-geography-service/@types/index.ts
  packages/mds-geography-service/client/index.ts
Labels: bulldozer-update, bulldozer-merge

#881 JSON.stringify() errors that are simple objects
  .changeset/afraid-vans-try.md
  packages/mds-utils/exceptions/exceptions.ts
  packages/mds-utils/utils.ts
Labels: bug, bulldozer-update, bulldozer-merge

#885 Add more details around the usage of Kafka & NATS to mds-stream readme
  packages/mds-stream/README.md
Labels: documentation, bulldozer-update, bulldozer-merge

#887 Rework ModelMapper type, remove unnecessary RpcServer type
  .changeset/shaggy-crews-explain.md
  .changeset/spicy-guests-tickle.md
  packages/mds-repository/mapper.ts
  packages/mds-rpc-common/server/index.ts
Labels: enhancement, bulldozer-update, bulldozer-merge

#888 Add swcrs to speed up Jest tests
  .changeset/dry-cougars-occur.md
  .changeset/old-garlics-switch.md
  .jest/jest.config.js
  .swcrc
  package.json
  packages/mds-geography-service/jest.config.js
  packages/mds-ingest-service/repository/entities/event-entity.ts
  packages/mds-ingest-service/repository/entities/telemetry-entity.ts
  packages/mds-repository/mixins/recorded-column.ts
  packages/mds-schema-validators/jest.config.js
  packages/mds-transaction-service/repository/entities/operation-entity.ts
  packages/mds-transaction-service/repository/entities/status-entity.ts
  packages/mds-transaction-service/repository/entities/transaction-entity.ts
  pnpm-lock.yaml
Labels: enhancement, bulldozer-update, bulldozer-merge

#882 [PLAT-367] Add Taxi State Machine Validation Utils & getDeviceEvents method to Ingest Service
  .changeset/sharp-starfishes-pump.md
  .changeset/sour-cameras-sneeze.md
  packages/mds-ingest-service/@types/index.ts
  packages/mds-ingest-service/client/index.ts
  packages/mds-ingest-service/repository/index.ts
  packages/mds-ingest-service/service/manager.ts
  packages/mds-ingest-service/service/provider.ts
  packages/mds-ingest-service/tests/index.spec.ts
  packages/mds-utils/state-machine.ts
  packages/mds-utils/tests/utils.spec.ts
Labels: enhancement, bulldozer-update, bulldozer-merge

#884 Make mds-policy-service kafka writes optional
  .changeset/wise-coats-brush.md
  packages/mds-policy-service/service/provider.ts
  packages/mds-policy-service/tests/policy-client.spec.ts
Labels: enhancement, bulldozer-update, bulldozer-merge

#892 Remove mds-config-files references in helm chart, remove helm/mds/files symlink
  helm/mds/files
  helm/mds/templates/deployment.yaml
Labels: tech-debt, bulldozer-update, bulldozer-merge

#904 [PLAT-388] Add duration format to SchemaValidators in accordance with JSONSchema Draft 2019-09
  .changeset/yellow-flies-ring.md
  packages/mds-schema-validators/index.ts
  packages/mds-schema-validators/tests/schema-validator.spec.ts
  packages/mds-schema-validators/tests/test.schema.ts
Labels: enhancement, bulldozer-update, bulldozer-merge

#909 First pass at trying to add tests through Github Actions...
  .github/workflows/run-tests.yaml
Labels: tech-debt, bulldozer-update, bulldozer-merge

#913 Remove useless mds-db tests
  packages/mds-db/package.json
  packages/mds-db/tests/helpers.ts
  packages/mds-db/tests/mds-db.spec.ts
Labels: bug, bulldozer-update, bulldozer-merge

#910 Use separate metadata file for each repository
  .changeset/khaki-trainers-decide.md
  packages/mds-ingest-service/repository/migrations/1633182766754-CreateEventsWithDeviceAndTelemetryInfoView.ts
  packages/mds-ingest-service/repository/migrations/1634672590753-ChangeEventsWithDeviceAndTelemetryInfoToUseInnerJoin.ts
  packages/mds-ingest-service/repository/migrations/1645465504597-CopyIngestMigrationMetadata.ts
  packages/mds-ingest-service/repository/migrations/index.ts
  packages/mds-repository/repository.ts
Labels: bulldozer-update, bulldozer-merge
